---
apiVersion: agentnet/v1alpha1
kind: AgentDefinition
metadata:
  name: triageAgent
  namespace: customerSupport
spec:
  io:
    - type: NatsIO
      bindings:
        discoveryTopic: customerSupport.discovery
        acceptedNetworks: 
          - "customerSupport.*"
  store:
    type: Memory
  llm:
    provider: Gemini
    model: gemini-2.0-flash
    systemInstruction: |
      You are a customer support triage agent. Your role is to:
      1. Greet customers professionally and warmly
      2. Understand their query or issue
      3. Categorize their inquiry accurately
      4. Route them to the appropriate specialized agent
      
      Categories include:
      - Product questions (features, specs, compatibility)
      - Technical issues (setup problems, bugs, troubleshooting)
      - Billing concerns (payments, subscriptions, refunds)
      - Complex issues requiring special attention
      
      Make the customer feel heard and ensure their issue is sent to the right specialist.
    config:
      temperature: 0.3
      toolConfig:
        functionCallingConfig:
          mode: 'auto'
  
  tools:
    - name: categorizeQuery
      description: Analyze a customer query and determine its category
      parameters:
        type: object
        properties:
          query:
            type: string
            description: The customer's full query or issue description
        required:
          - query
    
    - name: routeToAgent
      description: Route the customer to the appropriate specialized agent
      parameters:
        type: object
        properties:
          category:
            type: string
            description: The category of the customer's query (product, technical, billing, complex)
          queryId:
            type: string
            description: Unique identifier for this customer query
          customerInfo:
            type: object
            description: Customer information if available
        required:
          - category
          - queryId

---
apiVersion: agentnet/v1alpha1
kind: AgentDefinition
metadata:
  name: productAgent
  namespace: customerSupport
spec:
  io:
    - type: NatsIO
      bindings:
        discoveryTopic: customerSupport.discovery
  store:
    type: Memory
  llm:
    provider: Gemini
    model: gemini-2.0-flash
    systemInstruction: |
      You are a product specialist agent in customer support. Your role is to:
      1. Answer questions about product features and specifications
      2. Explain product compatibility with other systems
      3. Help customers understand product capabilities
      4. Suggest the right product based on customer needs
      
      Be knowledgeable, accurate, and helpful. If a question falls outside your expertise,
      suggest routing to a more appropriate agent.
    config:
      temperature: 0.3
      toolConfig:
        functionCallingConfig:
          mode: 'auto'
  
  tools:
    - name: getProductInfo
      description: Retrieve information about a specific product
      parameters:
        type: object
        properties:
          productId:
            type: string
            description: The ID of the product to get information about
          infoType:
            type: string
            description: The type of information needed (specs, features, compatibility)
        required:
          - productId
    
    - name: compareProducts
      description: Compare features between multiple products
      parameters:
        type: object
        properties:
          productIds:
            type: array
            items:
              type: string
            description: Array of product IDs to compare
        required:
          - productIds
  
  discoverySchemas:
    - name: product_agent_query
      description: Handle product-related customer inquiries
      parameters:
        type: object
        properties:
          question:
            type: string
            description: The customer's product-related question
          productContext:
            type: object
            description: Additional context about the products being discussed
        required:
          - question

---
apiVersion: agentnet/v1alpha1
kind: AgentDefinition
metadata:
  name: technicalAgent
  namespace: customerSupport
spec:
  io:
    - type: NatsIO
      bindings:
        discoveryTopic: customerSupport.discovery
  store:
    type: Memory
  llm:
    provider: Gemini
    model: gemini-2.0-flash
    systemInstruction: |
      You are a technical support specialist agent. Your role is to:
      1. Help troubleshoot technical issues with products
      2. Guide customers through setup and configuration
      3. Diagnose problems and suggest solutions
      4. Provide step-by-step technical instructions
      
      Be patient, thorough, and explain technical concepts clearly. If an issue is 
      particularly complex, consider escalating to the escalation agent.
    config:
      temperature: 0.3
      toolConfig:
        functionCallingConfig:
          mode: 'auto'
  
  tools:
    - name: troubleshootIssue
      description: Analyze a technical issue and provide troubleshooting steps
      parameters:
        type: object
        properties:
          issueDescription:
            type: string
            description: Description of the technical issue
          productId:
            type: string
            description: The ID of the product having issues
          systemInfo:
            type: object
            description: Customer's system information if available
        required:
          - issueDescription
    
    - name: checkKnownIssues
      description: Check if the reported issue matches any known issues
      parameters:
        type: object
        properties:
          symptoms:
            type: array
            items:
              type: string
            description: List of symptoms or error messages
          productId:
            type: string
            description: The ID of the product
        required:
          - symptoms
  
  discoverySchemas:
    - name: technical_agent_query
      description: Handle technical support issues and troubleshooting
      parameters:
        type: object
        properties:
          issue:
            type: string
            description: Description of the technical issue
          productInfo:
            type: object
            description: Information about the product having issues
        required:
          - issue

---
apiVersion: agentnet/v1alpha1
kind: AgentDefinition
metadata:
  name: billingAgent
  namespace: customerSupport
spec:
  io:
    - type: NatsIO
      bindings:
        discoveryTopic: customerSupport.discovery
  store:
    type: Memory
  llm:
    provider: Gemini
    model: gemini-2.0-flash
    systemInstruction: |
      You are a billing and accounts specialist agent. Your role is to:
      1. Help with payment-related inquiries
      2. Address subscription concerns
      3. Process refund requests
      4. Explain billing policies and procedures
      
      Be accurate, discreet, and helpful with financial matters. Maintain customer privacy
      and security when discussing account details.
    config:
      temperature: 0.3
      toolConfig:
        functionCallingConfig:
          mode: 'auto'
  
  tools:
    - name: getAccountInfo
      description: Retrieve a customer's account information
      parameters:
        type: object
        properties:
          customerId:
            type: string
            description: The customer's unique identifier
          infoType:
            type: string
            description: Type of account info needed (payment history, subscription details, etc.)
        required:
          - customerId
    
    - name: processRefund
      description: Process a refund request
      parameters:
        type: object
        properties:
          orderId:
            type: string
            description: The order ID for the purchase to be refunded
          reason:
            type: string
            description: Reason for the refund request
          fullRefund:
            type: boolean
            description: Whether a full or partial refund is requested
        required:
          - orderId
          - reason
  
  discoverySchemas:
    - name: billing_agent_query
      description: Handle billing, payment, and subscription inquiries
      parameters:
        type: object
        properties:
          question:
            type: string
            description: The customer's billing-related question
          accountContext:
            type: object
            description: Additional context about the customer's account
        required:
          - question

---
apiVersion: agentnet/v1alpha1
kind: AgentDefinition
metadata:
  name: escalationAgent
  namespace: customerSupport
spec:
  io:
    - type: NatsIO
      bindings:
        discoveryTopic: customerSupport.discovery
  store:
    type: Memory
  llm:
    provider: Gemini
    model: gemini-2.0-flash
    systemInstruction: |
      You are an escalation specialist agent for complex support issues. Your role is to:
      1. Handle difficult or unique customer problems
      2. Address issues that couldn't be resolved by other agents
      3. Provide specialized expertise for complex scenarios
      4. Coordinate with multiple teams when necessary
      
      You have a deeper level of access and authority. Be thorough, patient, and
      focus on resolution even for the most challenging issues.
    config:
      temperature: 0.3
      toolConfig:
        functionCallingConfig:
          mode: 'auto'
  
  tools:
    - name: analyzeComplexIssue
      description: Analyze a complex customer issue that requires special handling
      parameters:
        type: object
        properties:
          issueDescription:
            type: string
            description: Detailed description of the complex issue
          previousAttempts:
            type: array
            items:
              type: object
            description: Previous attempts to resolve the issue
          customerHistory:
            type: object
            description: Relevant customer history
        required:
          - issueDescription
    
    - name: createSpecializedSolution
      description: Create a customized solution for a complex issue
      parameters:
        type: object
        properties:
          issueId:
            type: string
            description: ID of the complex issue
          approachType:
            type: string
            description: Type of approach to use for the solution
        required:
          - issueId
  
  discoverySchemas:
    - name: escalation_agent_query
      description: Handle complex, escalated customer support issues
      parameters:
        type: object
        properties:
          complexIssue:
            type: string
            description: Description of the complex issue requiring escalation
          history:
            type: object
            description: History of previous support attempts
        required:
          - complexIssue

---
apiVersion: agentnet/v1alpha1
kind: AgentDefinition
metadata:
  name: followupAgent
  namespace: customerSupport
spec:
  io:
    - type: NatsIO
      bindings:
        discoveryTopic: customerSupport.discovery
  store:
    type: Memory
  llm:
    provider: Gemini
    model: gemini-2.0-flash
    systemInstruction: |
      You are a customer follow-up specialist agent. Your role is to:
      1. Check in with customers after their issues have been addressed
      2. Verify that solutions were satisfactory
      3. Collect feedback on the support experience
      4. Identify any remaining concerns
      
      Be personable, appreciative of their time, and genuinely interested in their
      satisfaction. If new issues are found, route them back to the triage agent.
    config:
      temperature: 0.3
      toolConfig:
        functionCallingConfig:
          mode: 'auto'
  
  tools:
    - name: checkResolutionStatus
      description: Check if a customer issue was fully resolved
      parameters:
        type: object
        properties:
          caseId:
            type: string
            description: The case ID for the support interaction
        required:
          - caseId
    
    - name: recordFeedback
      description: Record customer feedback on their support experience
      parameters:
        type: object
        properties:
          caseId:
            type: string
            description: The case ID for the support interaction
          feedbackType:
            type: string
            description: Type of feedback (satisfaction rating, comments, suggestions)
          feedbackContent:
            type: string
            description: The actual feedback provided by the customer
        required:
          - caseId
          - feedbackType
          - feedbackContent
  
  discoverySchemas:
    - name: followup_agent_query
      description: Follow up with customers after support interactions
      parameters:
        type: object
        properties:
          caseId:
            type: string
            description: The case ID to follow up on
          interactionSummary:
            type: string
            description: Summary of the previous support interaction
        required:
          - caseId 